hide_window_decorations yes

font_family JetbrainsMono Nerd Font
font_size 14.5

background_opacity 0.8
background_blur 1

# background #252930
# background #1e2127
# background #1a1d23

# background #1f2430
# background #161821
# background #14151e
